GET https://one-sprint-mission-be-svjo.onrender.com/products

###
POST https://one-sprint-mission-be-svjo.onrender.com/products
Content-Type: application/json

{
  "name": "아이폰 15",
  "description": "아이폰 15",
  "price": 610000,
  "tags": ["전자제품", "모바일"],
  "favoriteCount": 52
}