GET https://one-sprint-mission-be-svjo.onrender.com/products

###
POST https://one-sprint-mission-be-svjo.onrender.com/products
Content-Type: application/json

{
  "name": "갤럭시 탭 S7",
  "description": "삼성 갤럭시 탭 S7",
  "price": 350000,
  "favoriteCount": 32,
  "tags": ["전자제품", "모바일"]
}